### ISSUE TITLE
The website is not very smooth

### ISSUE THREAD

**Issue by JE-lee** [xiaoluoboding/vue-color-wheel#1]
I have noticed that there are always some CPU tasks in the background. What was the cause of that?
![image](https://github.com/xiaoluoboding/vue-color-wheel/assets/19794813/831f6606-02ee-4ddf-9163-3d2769b5b3b0)

**Comment by xiaoluoboding** [comment]
It must be due to the dynamic gradient color. I will optimize it.

**Comment by simonspg** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hug6, @killeder, @geekwho-eth, @telmag92, @vihermawan, @sdfsdfsdf145314364, @zhouzh1, @talentlessguy, @garNUE, @GoBGI, @RayMusk, @DeepEffort, @adshao, @Colorize8, @JacksonRed, @XMan-O, @RawAttack, @NissinFree, @tufo830, @zakimzf, @17737787811, @chuangjiantx123, @asyuan, @solo-tiger-man, @wgqzlj, @weixiaojian001, @emanuelb, @siuisa, @libtree, @0xd0a, @fpdb, @heisaman, @ValiAlex, @devout1337, @RogueBeef, @PHSix, @luyl, @CreaKiko, @TenviLi, @Hope-Diamond, @stackia, @gikoluo, @tuanductran, @soucat, @MoonWindow, @kakegu, @tildaw27, @i0Ek3, @Yinboan, @Askar57gianghungtien, @Rongrongku, @kai2k9, @appfromape, @less-cat, @tuananh9801, @billyma128, @innaturn, @111hunter, @upstemer-hash, @ChieKR, @kittyFishing, @kakegu, @canisminor1990, @coder-drinker, @zjxubinbin, @futanar1, @zsgzzzf, @bandyishere, @hyzhao1998, @cybernagle, @Fog3211, @orxia, @WinDB3ll, @Alejanpro, @usherasnick, @Antisunny, @1984Zenith, @Lugdunumn, @GlamRing, @HardDevel, @misc520, @Weo6, @molierflower, @Rita-Xizu, @nj-steve, @Bruce1998, @leeleoo, @mvandermeulen, @sunnala, @lhw619, @xiaojunma960, @gsZhiZunBao, @stdedit, @whatwewant, @haujoe, @src-chen, @NewHappy1024, @dashen8888, @MonchiLin

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
weboAp, @vbrekher, @pizzamanblabla, @dliuproduction, @english4coder, @phrazzld, @jueewo, @afxal, @ArnaudFavier, @siburu, @christianzoll, @mowinters, @EdgarHSalinas, @QuynhNguyen, @changjieyang01, @jzarca01, @bbrietzke, @yalcincosar, @stepcellwolf, @rockf91, @zero85258, @KeanuPang, @ndphuong, @igardiet, @Ractive89, @ohitslaurence, @erhant, @NicolasLeRoux, @dorucioclea, @lleonesouza, @beblueblue, @wgqzlj, @Koleok, @MarioJuniorPro, @forrestsatterfield, @und3fined, @wesleysmyth, @jinchun, @xox9001, @luoposhanhuige, @CodeJonesW, @kaichen, @khantzinthu2k1, @boroda413, @Demontf, @siong1987, @sptq, @zaa, @GaloisField2718, @xianz271828zoexx, @ujjwalgoyal19, @KshitijV97, @leandrogavidia, @puzzithinker, @b33l238u8, @EdsonAlcala, @strawhatboy, @ess007, @tugh, @desfero, @Lainvers, @nimatr, @alphadose, @Artikodin, @zeyuanx, @christon1, @jjyr, @itsky365, @flozender, @josojo, @RicoloveFeng, @kaiyes, @dsmagic12, @henriquecouto, @web3senior, @w1ndyz, @amohammad, @bitloo, @NexZhu, @shinyzhu, @vsboldakov, @schmijos, @sshhaatteerr, @aozkan, @iida-hayato, @izayacity, @taywils, @mdeyn, @Lifehack-crypto, @code-miller, @readygo67, @capaci, @keithadams, @tsvillain, @duanjunxiao, @jyterencekim, @Lisayg, @beaubutton, @jinsley8
